// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khypaefifqlgqlpkhxck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeXBhZWZpZnFsZ3FscGtoeGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzQ3MzUsImV4cCI6MjA3MDg1MDczNX0.mVg7DbTuBn-rj6Sq7sZdWPaTP_RCy6xA1d6BLE3aTUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});